spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org: WARN
    fr: TRACE

    jpa:
      hibernate:
        ddl-auto: update
    jackson:
      date-format: "yyyy ss hh mm dd ww MM"


